import{a as $,i as g,S as q}from"./assets/vendor-Ca8cN8cH.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const r of o.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&s(r)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();async function y(i,t=1){try{const a=await $.get("https://pixabay.com/api/",{params:{key:"50312672-6ff896f2a2c8f700d68e76dd9",q:i,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15}}),{hits:s,totalHits:e}=a.data;return s.length===0?(g.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",titleColor:"white",messageColor:"white"}),{images:[],totalHits:0}):{images:s.map(r=>({webformatURL:r.webformatURL,largeImageURL:r.largeImageURL,tags:r.tags,likes:r.likes,views:r.views,comments:r.comments,downloads:r.downloads})),totalHits:e}}catch{throw new Error("Помилка при отриманні зображень з Pixabay API")}}const h=document.querySelector(".gallery"),p=document.querySelector(".loader"),b=document.querySelector(".load-more");let P=new q(".gallery a",{captions:!0,captionsData:"title",captionDelay:250,captionPosition:"bottom"});function w(i){const t=i.map(({webformatURL:a,largeImageURL:s,tags:e,likes:o,views:r,comments:u,downloads:m})=>`
      <li class="gallery-item">
        <a href="${s}" class="image-container" alt="${e}">
          <img src="${a}"
               alt="${e}"
               title="Likes: ${o} | Views: ${r} | Comments: ${u} | Downloads: ${m}" />
          <div class="info-overlay">
            <div class="info-item"><b>Likes</b>: ${o}</div>
            <div class="info-item"><b>Views</b>: ${r}</div>
            <div class="info-item"><b>Comments</b>: ${u}</div>
            <div class="info-item"><b>Downloads</b>: ${m}</div>
          </div>
        </a>
      </li>`).join("");h.insertAdjacentHTML("beforeend",t),P.refresh()}function C(){h.innerHTML=""}function L(){p.classList.add("is-visible")}function v(){p.classList.remove("is-visible")}function E(){b.classList.remove("is-hidden")}function S(){b.classList.add("is-hidden")}function l(i,t="info"){g[t]({message:i,position:"topRight",backgroundColor:t==="error"||t==="warning"?"#ef4040":"#f0ad4e",titleColor:"white",messageColor:"white"})}const M=document.querySelector(".form"),f=document.querySelector(".input"),I=document.querySelector(".load-more");let c="",n=0,d=0;const R=15;M.addEventListener("submit",x);I.addEventListener("click",H);async function x(i){if(i.preventDefault(),c=f.value.trim(),!c)return l("Будь ласка, введіть запит","warning");n=1,S(),C(),L();try{const{images:t,totalHits:a}=await y(c,n);w(t),d=Math.ceil(a/R),n<d&&E()}catch{l("Виникла помилка при завантаженні. Спробуйте ще раз.","error")}finally{v()}f.value=""}async function H(){n++,L();try{const{images:i}=await y(c,n);w(i);const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),n>=d&&(S(),l("We are sorry, but you've reached the end of search results","info"))}catch{l("Виникла помилка при завантаженні. Спробуйте ще раз.","error")}finally{v()}}
//# sourceMappingURL=index.js.map
